name: Send changed files on PR

on:
    pull_request:
        types: [opened, synchronize]

jobs:
  send-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to get full history for diff

      - name: Get changed files
        id: files
        run: |
          # Get list of changed files in the PR
          files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }} | jq -R -s -c 'split("\n")[:-1]')
          echo "changed_files=$files" >> $GITHUB_OUTPUT

      - name: Send changed files to API endpoint
        env:
          API_URL: https://617e-2409-40f0-1048-f538-3da0-cacc-b70a-1cfb.ngrok-free.app/item
          CHANGED_FILES: ${{ steps.files.outputs.changed_files }}
        run: |
          echo "Sending changed files: $CHANGED_FILES"
          curl -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -d "{\"changed_files\": $CHANGED_FILES}"
