name: Hello world


on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: HEllo wstep
        run: echo "hello world"
