name: Hello world


on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: HEllo wstep
        run: echo "hello world"
  
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: hello1 world
        run: echo "hello11 world"